routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::post('/home/filter', 'HomeController@filter')->name('home.filter');
Route::resource('/home', 'HomeController');

app/User.php
<?php

namespace SWA;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'dni', 'first_name', 'last_name', 'email', 'phone', 'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function loan(){
        //relacion de de uno a muchos entre role y user
        return $this->hasMany(Loan::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace SWA\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace SWA\Http\Controllers;

use Illuminate\Http\Request;
use SWA\User;
use Auth;
use Carbon\Carbon;
use GuzzleHttp\Client;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Muestra la página inicial del sistema
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $client = new Client(['base_uri' => 'https://swapi.co/api/']);

        $response = $client->request('GET', 'people');
        $characters = json_decode($response->getBody()->getContents())->results;

        $species = HomeController::getSpecies($characters);

        return view('home')->with([
            'characters' => $characters,
            'species' => $species
        ]);
    }

    /**
     * Permite redirijir a la vista que permitira registrar el prestamo
     */
    public function create()
    {
        //
    }

    /**
     * Método que permite registrar el pago.
     * @param [CreateRequest] parametro que permite validar los datos
     * del formulario a través del Forn Request de laravel
     * @var [$request] Request con todos los datos provenientes del formulario
     * de solicitud de credito.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Método que permitira mostrar los datos especificos de un prestamo.
     */
    public function show($id)
    {
        $client = new Client(['base_uri' => 'https://swapi.co/api/']);

        $response = $client->request('GET', 'people/'.$id);
        $character = json_decode($response->getBody()->getContents());

        return view('show')->with([
            'character' => $character
        ]);
    }

    public function filter(Request $request)
    {
        $client = new Client(['base_uri' => 'https://swapi.co/api/']);

        $response = $client->request('GET', 'people');
        $characters = json_decode($response->getBody()->getContents())->results;

        if ( strcmp($request->species,"All") !== 0 ) {
            $species = [];
            $characters = HomeController::getDistinct($characters,$request->species,$species);
        }else {
            $species = HomeController::getSpecies($characters);
        }

        return view('home')->with([
            'characters' => $characters,
            'species' => $species
        ]);
    }

    public function getDistinct($all, $particular, &$species)
    {
        $base_url = "https://swapi.co/api/";

        $client = new Client(['base_uri' => $base_url]);

        $result = [];

        foreach ($all as $key){
            $route = substr($key->species[0],strlen($base_url));
            $response = $client->request('GET', $route);
            $specie = json_decode($response->getBody()->getContents());

            if (!in_array($specie->name,$species)) {
                $species[] = $specie->name;
            }

            if ($specie->name == $particular) {
                $result[] = $key;
            }
        }

        return $result;
    }

    public function getSpecies($all)
    {
        $base_url = "https://swapi.co/api/";

        $client = new Client(['base_uri' => $base_url]);

        $distinct = [];

        foreach ($all as $key){
            $route = substr($key->species[0],strlen($base_url));
            $response = $client->request('GET', $route);
            $specie = json_decode($response->getBody()->getContents());

            if (!in_array($specie->name,$distinct)) {
                $distinct[] = $specie->name;
            }
        }

        return $distinct;
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    Character List
                </div>
                @include('flash::message')
                <div class="panel-body">
                    <label for="amount_limit">StarWars</label>
                    <form action="{{ route('home.filter') }}" method="POST" >
                      {{ csrf_field() }}
                      <div class="row">
                          <div class="col-md-12">
                              <label for="species" class="control-label">Species Filter</label>
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-md-9">
                              <select id="species" name="species" class="form-control">
                                  <option value="All">All</option>
                                  @php
                                      $i = 1;
                                  @endphp
                                  @foreach($species as $data)
                                      <option value="{{ $data }}">{{ $data }}</option>
                                      @php
                                          $i++;
                                      @endphp
                                  @endforeach
                              </select>
                          </div>
                          <div class="col-md-3">
                              <button type="submit" class="btn btn-default btn-block btn-primary">Buscar</button>
                          </div>
                      </div>
                    </form>
                    @include('table')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('vendor/font-awesome/css/font-awesome.css') }}?4.70">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->first_name . ' ' . Auth::user()->last_name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
 <div class="row">
     <div class="col-md-8 col-md-offset-2">
         <div class="panel panel-default">
            <div class="panel-heading clearfix">
                Feature List
                <div class="pull-right text-center">
                     <a href="{{ route('home.index') }}" type="button" class="btn ">Atrás</a>
                </div>
            </div>
            <div class="panel-heading clearfix">
                <div class="form-group">
                  <label for="name"><strong>Name:</strong> {{ $character -> name }}</label>
                </div>
               <div class="form-group">
                 <label for="skin_color">Skin Color: {{ $character -> skin_color }}</label>
               </div>
               <div class="form-group">
                 <label for="eye_color">Eye Color: {{ $character -> eye_color }}</label>
               </div>
               <div class="form-group">
                 <label for="birth_year">Birth Year: {{ $character -> birth_year }}</label>
               </div>
               <div class="form-group">
                 <label for="gender">Gender: {{ $character -> gender }}</label>
               </div>
           </div>
     </div>
 </div>
</div>
@endsection

resources/views/table.blade.php
<table class="table table-hover text-center">
    <thead>
        <th class="text-center">Name</th>
        <th class="text-center">Height</th>
        <th class="text-center">Mass</th>
        <th class="text-center">Hair Color</th>
    </thead>
    <tbody>
        @if (isset($characters))
            @php
                $i = 1;
            @endphp
            @foreach ($characters as $key)
                <tr>

                    <td class="text-capitalize"><a href="{{ route('home.show',$i) }}">
                        @if ($key->gender == 'male')
                            <i class="fa fa-male" aria-hidden="true"></i>
                        @elseif ($key->gender == 'female')
                            <i class="fa fa-female" aria-hidden="true"></i>
                        @else
                            <i class="fa fa-android" aria-hidden="true"></i>
                        @endif {{ $key->name }}</a></td>

                    <td>{{ $key->height }}</td>
                    <td>{{ $key->mass }}</td>
                    <td>{{ $key->hair_color }}</td>
                </tr>
                @php
                    $i++;
                @endphp
            @endforeach
        @else
            <tr>
                <label for="sin_data">No hay personajes.</label>
            </tr>
        @endif
    </tbody>
</table>